### ISSUE TITLE
执行 (c)npm i --> gulp --> node index.js 后3333端口处于监听状态，但浏览器无法打开页面？

### ISSUE THREAD

**Issue by JounQin** [jzlxiaohei/webpack-coc-demo#4]
将项目 clone 到本地后执行情况如下：

```
 /local/GitHub/webpack-coc-demo/ [master*] cnpm i
npm WARN EPACKAGEJSON webpack-coc@0.0.1 No repository field.
npm WARN EPACKAGEJSON webpack-coc@0.0.1 license should be a valid SPDX license expression
 /local/GitHub/webpack-coc-demo/ [master] gulp
[15:30:34] Using gulpfile /local/GitHub/webpack-coc-demo/gulpfile.js
[15:30:34] Starting 'clean'...
[15:30:34] Finished 'clean' after 34 ms
[15:30:34] Starting 'lib'...
[ 'lib-f611f2d05eab9e98a041.js',
  'lib-f611f2d05eab9e98a041.css',
  'lib-f611f2d05eab9e98a041.js.map',
  'lib-f611f2d05eab9e98a041.css.map' ]
[15:30:37] Finished 'lib' after 2.58 s
[15:30:37] Starting 'default'...
{ 'contact.entry': '/local/GitHub/webpack-coc-demo/assets/src/contact/contact.entry.js',
  'index.entry': '/local/GitHub/webpack-coc-demo/assets/src/index/index.entry.js',
  'other.entry': '/local/GitHub/webpack-coc-demo/assets/src/other/other.entry.js' }
[15:30:37] Finished 'default' after 26 ms
 /local/GitHub/webpack-coc-demo/ [master*] node index.js
server start:3333
```

打开浏览器`http://localhost:3333/index.html`提示`Cannot GET /index.html `

求问是否还需要进行其他配置？

**Comment by JounQin** [comment]
看了下 `index.js` 里 `app.use(express.static(__dirname + '/assets/dist'))`，生成的 `dist` 目录下还有 `webpack_coc` 子目录，所以访问路径应该是 `http://localhost:3333/webpack_coc/index.html`。

但是打开页面还是报错：
``` javascript
Uncaught ReferenceError: require is not defined
Uncaught TypeError: Cannot read property 'Component' of undefined
```

请问是否还有其他设置需要调整？

**Comment by jzlxiaohei** [comment]
首先抱歉，这个demo我后面没有跟进。

问题是 `react-dom.min.js` 中一定代码的判断机制，和`webpack`的打包冲突了。具体的，react-dom.min.js 里会通过`if("object"==typeof exports&&"undefined"!=typeof module)`判断是不是`commonjs`环境，浏览器端这里的判断应该是false，但是webpack自己的打包机制，会使这句话变`true`

你可以吧 `webpack.production.js`中的externals，noParse，resolve中关于react和react-dom的东西都去掉，这样react和react-dom 不会打包进lib，而是安装常规方式打包。

但是这样打包的速度巨慢，我自己在实际环境中，是把react.min.js 和 react-dom.min.js直接用`uglifyjs`简单的合并。不使用webpack，类似于直接引用cdn的方式。(这时externals，noParse，resolve就不要请去掉了）我在自己的`webpack-coc`中，就是这样处理的，用在工程上，目前还挺好的。不过webpack-coc包装的太深，我有进一步改造的计划。

强烈建议你通过cdn的方式引入react和react-dom，不然引人多个react的版本，还容易出问题。

**Comment by jzlxiaohei** [comment]
@JounQin 上面是原因，有个解决方案，把noParse里的`react-dom`的path删掉。

[源码](https://github.com/jzlxiaohei/webpack-coc-demo/blob/master/webpack.production.js#L60)
