### ISSUE TITLE
生产环境代码输出问题

### ISSUE THREAD

**Issue by datoulei** [jzlxiaohei/webpack-coc-demo#5]
我按照您给的例子把生产环境代码输出都没有问题，但是在访问的时候会出现错误。
在react-dom.min.js加载时出现了Uncaught ReferenceError: require is not defined

**Comment by jzlxiaohei** [comment]
不好意思，放假刚回来。
详见https://github.com/jzlxiaohei/webpack-coc-demo/issues/4
